# Generated by Django 4.2 on 2023-04-25 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nested_browsable", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="innermodel",
            old_name="parent",
            new_name="inner_parent",
        ),
        migrations.RenameField(
            model_name="middlemodel",
            old_name="parent",
            new_name="middle_parent",
        ),
    ]
