# Generated by Django 4.2 on 2023-04-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nested_browsable", "0002_rename_parent_innermodel_inner_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherInnerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                (
                    "inner_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_inner_children",
                        to="nested_browsable.middlemodel",
                        verbose_name="Parent instance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
